---
title: "task2"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(MASS)
library(mvtnorm)
library(dplyr)
library(qrnn)
library(tidyverse)
library(stats)
library(matrixcalc)
library(pracma)
library(janitor)
library(kableExtra)
library(knitr)
library(ggmap)
library(sp)
library(maptools)
library(maps)
library(ggrepel)
require(survival)
require(quantreg)
require(glmnet)
require(pROC)
library(pracma)
library(ModelMetrics)
library(readxl)
library(factoextra)
library(fpc)
```

## data cleaning

```{r}
df.raw = read.csv("covid19-1.csv")
df = df.raw %>% 
  janitor::clean_names() %>% 
  dplyr::select(country_region, province_state, date, confirmed_cases) %>% 
  filter(confirmed_cases != 0)

# region with confirm case > 20
df_country = df %>% 
  group_by(country_region) %>% 
  summarise(max=max(confirmed_cases)) %>% 
  filter(max > 20)

region_index = as.character(unique(df_country$country_region))

df.region = function(df, region) {
  df.r = df %>% 
    filter(country_region == region) %>% 
    group_by(country_region, date) %>% 
    summarise(cases = sum(confirmed_cases)) %>% 
    mutate(formal_date = as.Date(date, '%m/%d/%Y')) %>% 
    mutate(time = as.numeric(formal_date-min(formal_date)))%>% 
    arrange(time)  %>% 
    dplyr::select(region = country_region, date, time, cases)
  df.r
}

i= 1
df_list=vector("list", length = length(region_index))
while(i < length(region_index)+1){
  df_list[[i]]   = df.region(df, region_index[i])
  i = i+1
}

for (i in 1:length(df_list)){
names(df_list)[i] <- region_index[i]
}

```

```{r}
res = read_csv("./abc_values") %>% 
  dplyr::select(-X1) %>% 
  mutate(
    a_value = round(a_value,0),
    b_value = round(b_value,3),
    c_value = round(c_value,0)
  ) 

res[which(res$country_region == "China"), 2] = 7.873205*10^4
res[which(res$country_region == "China"), 3] = 0.22511
res[which(res$country_region == "China"), 4] = 17.91412

res[which(res$country_region == "Korea, South"), 2] = 8.801392e+03
res[which(res$country_region == "Korea, South"), 3] = 2.836325e-01
res[which(res$country_region == "Korea, South"), 4] = 4.038837e+01


all_t=NULL
for(c in 1:length(df_list))
all_t=rbind(all_t,df_list[[c]][nrow(df_list[[c]]),3])

sum((res[,4])<all_t[,1])# total country pass the mid point


names=res[which((res[,4])<all_t[,1]),1]# names of those country
```

## Task2

```{r}
EM = function(data,ncluster){
  data = as.matrix(data) %>% scale()
  n = nrow(data)
  q = ncol(data)
  p_j = rep(1/ncluster,ncluster)
  mu = data[sample(n,ncluster),] %>% as.matrix()
  covmat = diag(ncol(data))
  covlist = list()
  for(i in 1:ncluster){
    covlist[[i]] = covmat
  }

count = 1
while(count <100){     
  mu0 <- mu

  # E-step: Evaluate posterior probability, gamma     
  gamma <- c()     
  for(j in 1:ncluster){       
    gamma2 <- apply(data,1, dmvnorm, mean = mu[j,], sigma = covlist[[j]])       
    gamma <- cbind(gamma, gamma2)     
  }
    
   # M- step: Calculate mu     
  tempmat <- matrix(rep(p_j,n),nrow=n,byrow = T)     
  r <- (gamma * tempmat) / rowSums(gamma * tempmat)     
  mu <- t(r) %*% data / colSums(r)
  

  # M- step: Calculate Sigma and p     
  for(j in 1:ncluster){       
    sigma <- matrix(rep(0,q^2),ncol=q)       
    for(i in 1:n){         
      sigma = sigma + r[i,j] * (data[i,]-mu0[j,]) %*% t(data[i,]-mu0[j,])       }       
    covlist[[j]] <- sigma/sum(r[,j])     }    
  p_j <- colSums(r)/n    
  count = count + 1  }
  
  cluster <- which(r == apply(r, 1, max), arr.ind = T)   
  cluster <- cluster[order(cluster[,1]),]   
  return(list(mu = mu,covlist = covlist, p_j = p_j,cluster = cluster)) }
```

```{r}
em_dat = res %>% dplyr::select(-country_region) 
em_dat_scaled <- scale(em_dat)

## use wss
fviz_nbclust(em_dat_scaled, kmeans, method = "wss",k.max = 15)

## use silhouette
fviz_nbclust(em_dat_scaled, kmeans, method = "silhouette",k.max=15)

## use Gap Statistic Method
library(cluster)
set.seed(123)
gap_stat <- clusGap(em_dat_scaled, FUN = kmeans, nstart = 25,
                    K.max = 10, B = 50)
fviz_gap_stat(gap_stat)

set.seed(1)
res2 = EM(em_dat,3)
res3=res2$mu %>% 
  as.data.frame()
res3

set.seed(1)
clusters = kmeans(em_dat,3)
clusternumbers = as.factor(clusters$cluster)
```


```{r}
## res4 is the classification result of em and kmeans
res4 = res2$cluster %>% 
  as.data.frame() %>% 
  dplyr::select(-1) %>% 
  mutate(country = region_index ) %>% 
  dplyr::select(2,1) %>% 
  rename(GMM_class = col) %>% 
  mutate(
    kmeans_class = clusters$cluster
  ) %>% 
  mutate(
    a_value = res$a_value,
    b_value = res$b_value,
    c_value = res$c_value
  )

res4[1:50,] %>% 
  knitr::kable(booktabs = T, align = 'c')

res4[51:100,] %>% 
  knitr::kable(booktabs = T, align = 'c')

res4[101:116,] %>% 
  knitr::kable(booktabs = T, align = 'c')

kmean_mean = clusters$centers %>% 
  as.data.frame()

a_mean = mean(res$a_value)
a_sd = sd(res$a_value)
b_mean = mean(res$b_value)
b_sd = sd(res$b_value)
c_mean = mean(res$c_value)
c_sd = sd(res$c_value)
em_mean = res3 %>% 
  mutate(
    a_value = a_value*a_sd+a_mean,
    b_value = b_value*b_sd+b_mean,
    c_value = c_value*c_sd+c_mean,
  ) 

mean_value = rbind(em_mean,kmean_mean) %>% 
  mutate(method = c("GMM","GMM","GMM","Kmeans","Kmeans","Kmeans")) %>% 
  dplyr::select(c(4,1,2,3))

mean_value %>% 
  knitr::kable(booktabs = T, align = 'c')
```


```{r}
df_map = df.raw %>% 
  janitor::clean_names() %>% 
  dplyr::select(country_region, province_state, date, confirmed_cases, lat,long) %>% 
  filter(confirmed_cases != 0) %>% 
  group_by(country_region,lat,long) %>% 
  summarise(max=max(confirmed_cases)) %>% 
  filter(max > 20) %>% 
  as.data.frame() %>% 
  mutate(
    country_region = as.character(country_region)
  )

GMM_class = NULL
kmeans_class = NULL
for(i in 1:212){
  GMM_class[i] = res4[which(res4$country == df_map[i,1]),2]
  kmeans_class[i] = res4[which(res4$country == df_map[i,1]),3]
}
 
df_map = df_map %>% 
  mutate(
    GMM_class = GMM_class,
    kmeans_class = kmeans_class
  )

mp<-NULL 
 
mapworld<-borders("world",colour = "gray50",fill="white") #绘制基本地图
 
mp<-ggplot()+mapworld+ylim(-60,90)
 
df_map_1 = df_map %>% filter(GMM_class ==1)
df_map_2 = df_map %>% filter(GMM_class ==2)
df_map_3 = df_map %>% filter(GMM_class ==3)
 
mp2<-mp+geom_point(aes(x=long,y=lat,size=max),data = df_map_1,color="#0099CC")+scale_size(range=c(1,5)) +
geom_point(aes(x=long,y=lat,size=max),data = df_map_2,color="#FF6666")+scale_size(range=c(1,5)) +
geom_point(aes(x=long,y=lat,size=max),data = df_map_3,color="#E69F00")+scale_size(range=c(1,5)) +  
theme(legend.position = "none") 
 
## blue class1   red class2  yellow class3
mp2


df_map_5 = df_map %>% filter(kmeans_class ==1)
df_map_6 = df_map %>% filter(kmeans_class ==2)
df_map_7 = df_map %>% filter(kmeans_class ==3)
 
mp3<-mp+geom_point(aes(x=long,y=lat,size=max),data = df_map_5,color="#0099CC")+scale_size(range=c(1,5))+ geom_point(aes(x=long,y=lat,size=max),data = df_map_6,color="#FF6666")+scale_size(range=c(1,5))+
geom_point(aes(x=long,y=lat,size=max),data = df_map_7,color="#E69F00")+scale_size(range=c(1,5))+
theme(legend.position = "none") 

mp3 #
```

```{r}
d <- dist(em_dat_scaled, method = "euclidean")

plotcluster(em_dat, res2$cluster[,2])
plotcluster(em_dat, clusters$cluster)

km_stats <- cluster.stats(d,  clusters$cluster)
km_stats$dunn

gmm_stats <- cluster.stats(d,  res2$cluster[,2])
gmm_stats$dunn

method = c("Kmeans", "GMM")
Dunn_index = round(c(km_stats$dunn,gmm_stats$dunn),4)
cbind(method,Dunn_index) %>% as.data.frame() %>% 
  knitr::kable(booktabs = T, align = 'c')
```

