---
title: "xj"
author: "xj2249"
date: "4/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(qpcR)
```

# prepare data
```{r}
df.raw = read.csv("covid19-1.csv")
df = df.raw %>% 
  janitor::clean_names() %>% 
  dplyr::select(country_region, province_state, date, confirmed_cases) %>% 
  filter(confirmed_cases != 0)

# region with confirm case > 20
df_country = df %>% 
  group_by(country_region) %>% 
  summarise(max=max(confirmed_cases)) %>% 
  filter(max > 20)

region_index = as.character(unique(df_country$country_region))

df.region = function(df, region) {
  df.r = df %>% 
    filter(country_region == region) %>% 
    group_by(country_region, date) %>% 
    summarise(cases = sum(confirmed_cases)) %>% 
    mutate(formal_date = as.Date(date, '%m/%d/%Y')) %>% 
    mutate(time = as.numeric(formal_date-min(formal_date)))%>% 
    arrange(time)  %>% 
    dplyr::select(region = country_region, date, time, cases)
  df.r
}

i= 1
df_list=vector("list", length = length(region_index))
while(i < length(region_index)+1){
  df_list[[i]]   = df.region(df, region_index[i])
  i = i+1
}

for (i in 1:length(df_list)){
names(df_list)[i] <- region_index[i]
}

```

# Task 1.1
```{r}
# Objective function; minimize sse
sse <- function(data,par){
  exp_y = par[1]/( 1+exp(-par[2]*(data$t - par[3])) )
  sum((data$case-exp_y)^2)
}


# update function
update <- function(data,par){
  t = data$t
  y = data$case
  coef = lm(log(par[1]/y-1)~t)$coefficients
  par[2] = -coef[2]
  par[3] = coef[1]/par[2]
  
  e = 1 + exp(-par[2]*t+par[2]*par[3])
  par[1] = sum(y/e)/sum(1/e^2)
  return(par)
}

# coordinate function
get_coordinate <- function(data,f,start,tol = 1e-10, maxiter = 200){
    i = 0 
    cur = start
    obj = f(data,cur)
    res = c(i,cur,obj)
    pre_obj = -Inf
    while ( i < maxiter && abs(obj - pre_obj) > tol ){ 
        i = i + 1
        pre_obj = obj
        cur = update(data,cur)
        obj = f(data,cur)
        res = rbind(res,c(i,cur,obj))
        }
    return(res)
}

d1 <- filter(df3,`Country/Region` == "Australia")
ans <- get_coordinate(d1,sse,start = c(10000,1,40))

```


## method2 look for abc

```{r}
## transform beta
beta_trans = function(betavec) {
  a = betavec[1]
  b = betavec[2]
  c = betavec[3]
  a_trans = 1/a
  c_trans = b*c
  beta = c(a_trans, b, c_trans)
  return(beta)
}

## transform data
dat_trans = function(dat){
  dat = as.data.frame(dat)
  x = dat$time
  y = dat$cases
  y_trans = 1/y
  dat_trans = as.data.frame(cbind(x,y_trans))
  return(dat_trans)
}

beta_trans_back = function(betavec){
  a = 1/betavec[1]
  b = betavec[2]
  c = betavec[3]/b
  beta = c(a, b, c)
  return(beta)
}

## using transformed data to calculate gradient and hess
grad_hess <- function(dat, beta) {
  x = dat$x
  y = dat$y_trans
  a = beta[1]
  b = beta[2]
  c = beta[3]
  n = length(x)
  p = exp(-b*x+c)
  target = -sum((y-(a+a*p))^2)
  grad <- -c(2*n*a+2*a*sum(p^2)-2*sum(y)-2*sum(y*p)+4*a*sum(p),
            a^2*sum(p^2*(-2*x))-2*a*sum(y*p*(-x))+2*a^2*sum(p*(-x)),
            2*a^2*sum(p^2)-2*a*sum(y*p)+2*a^2*sum(p))
# gradient at betavec
  Hess <- -matrix(c(2*n+2*sum(exp(-2*b*x+2*c))+4*sum(p),
                    2*a*sum(p^2*(-2*x))-2*sum(y*p*(-x))+4*a*sum(p*(-x)),
                    4*a*sum(p^2)-2*sum(y*p)+4*a*sum(p), 
                    2*a*sum(p^2*(-2*x))-2*sum(y*p*(-x))+4*a*sum(p*(-x)),
                    a^2*sum(p^2*((-2*x)^2))-2*a*sum(y*p*x^2)+2*a^2*sum(p*x^2),
                    a^2*sum(p^2*(-4*x))-2*a*sum(y*p*(-x))+2*a*sum(p*(-x)),
                    4*a*sum(p^2)-2*sum(y*p)+4*a*sum(p), 
                    a^2*sum(p^2*(-4*x))-2*a*sum(y*p*(-x))+2*a*sum(p*(-x)),
                    4*a^2*sum(p^2)-2*a*sum(y*p)+2*a^2*sum(p)),
                    ncol=3, byrow = TRUE)
  eigen_hess = eigen(Hess)$values
# modified newtonpaphson to ensure ascent direction
  if(eigen_hess[1]<0 && eigen_hess[2]<0 && eigen_hess[3]<0){
    Hess = Hess
  }else{
    Hess = Hess-max(eigen_hess)*matrix(c(1,1,1,1,1,1,1,1,1),3,3)
  }
# Hessian at betavec
  return(list(target = target, grad = grad, Hess = Hess))
}

## using transformed data to calculate optimal solution
modified_NewtonRaphson <- function(dat,start, tol=1e-10,
                               maxiter = 200) {
  i <- 0
  cur <- start
  stuff <- grad_hess(dat,cur)
  res <- c(0, stuff$target, cur)
  prevtarget = Inf
  l = 1
  while(i < maxiter && abs(stuff$target - prevtarget) > tol)
 {
   i <- i + 1
   prevtarget <- stuff$target
   prev <- cur
   cur <- prev - solve(stuff$Hess) %*% stuff$grad
   stuff = grad_hess(dat,cur)
# step-halfing
   while(stuff$target <= prevtarget && l < 1000){
     stuff_orig = grad_hess(dat,prev)
     cur <- prev - (1/(2^l))*solve(stuff_orig$Hess) %*% stuff_orig$grad
     stuff = grad_hess(dat,cur)
     l= l+1
   }
   res <- rbind(res, c(i, stuff$target, cur))# Add current values to results matrix
 }
  return(res)}
```

# Estimated cases 
```{r}
f.logit=function(beta, t){
  a = beta[1]
  b = beta[2]
  c = beta[3]
  a/(1+exp(-b*(t-c)))
}
```

# 59~88
```{r}
dat_ori=df_list[[73]]


beta = beta_trans(c(5000,0.3,30))
dat = dat_trans(dat_ori)
ans_mod = modified_NewtonRaphson(dat,beta)

beta_trans_final=ans_mod[length(ans_mod[,1]),3:5]
beta_trans_back(beta_trans_final)

ggplot(aes(x=time,y=cases),data=dat_ori)+
  geom_point() +
  geom_point(aes(x = time, 
                 y = f.logit(beta_trans_back(beta_trans_final),dat_ori$time)),
                 col = "red"
             )
view(dat_ori)
```
60 - c(4000,0.3,30) 24.3503253  0.4864149  4.2675793 what???
61 - c(1500,0.2,30) 1500.0    0.2   30.0
62 - c(2000,0.2,33) 2000.0    0.2   33.0
63 - c(2500,0.1,50) 2500.0    0.1   50.0
64 - c(2500,0.15,40) 2500.00    0.15   40.00
65 - c(5000,0.2,30) 5e+03 2e-01 3e+01
-------
67 - c(2000,0.4,30) 293.5529394   0.2235518  21.1788590
68 - c(2000,0.5,30) 829.2048134   0.1704021  36.5513180
69 - c(2000,0.3,30) 39.733295  0.546995  4.774547
-------
71 - c(2000,0.2,30) 531.8086527   0.3722294  17.0832143
72 - c(3000,0.3,30) 4103.8895818    0.1457548   62.2763822 what???
-------
74 - c(1500,0.2,30)  1500.0    0.2   30.0
75 - c(15000,0.2,30) 15000.0     0.2    30.0
76 - c(6500,0.2,40)  6500.0    0.2   40.0
-------
78 - c(2500,0.26,35) 7535.6042440    0.1852021   50.8536580
79 - c(7000,0.3,40)  3159.4714509    0.5837074   14.0027153
80 - c(2000,0.3,30)  93.7282241  0.2001453 19.1515774
81 - c(4000,0.2,32)  4000.0    0.2   32.0
-------
83 - c(400,0.3,20)   351.1940925   0.2993035  20.0321770
84 - c(400,0.3,20)   400.169533   0.535729  11.376814
-------
86 - c(3000,0.2,34) 972.2336399   0.5158945  13.5413497
87 - c(15000,0.2,30) 15000.0     0.2    30.0
88 - c(5000,0.2,30)  521.375230   0.610052  10.139379