---
title: "project 3"
author: "Qi Yuchen, yq2279"
date: "2020/4/19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stats)
library(matrixcalc)
library(pracma)
library(qpcR)
```

## data import and cleaning

```{r}
df.raw = read.csv("covid19-1.csv")
df = df.raw %>% 
  janitor::clean_names() %>% 
  dplyr::select(country_region, province_state, date, confirmed_cases) %>% 
  filter(confirmed_cases != 0)

region.index = levels(df$country_region)

# first step to write a function
df.china = df %>% 
  filter(country_region == region.index[30]) %>% 
  group_by(country_region, date) %>% 
  summarise(cases = sum(confirmed_cases)) %>% 
  mutate(formal_date = as.numeric(as.character(as.Date(date, '%m/%d/%Y'), format="%Y%m%d"))) %>% 
  mutate(time = formal_date-min(formal_date)) %>% 
  dplyr::select(region = country_region, date, time, cases) %>% 
  arrange(time)

# function to get data for a specific region
df.region = function(df, region) {
  df.r = df %>% 
    filter(country_region == region) %>% 
    group_by(country_region, date) %>% 
    summarise(cases = sum(confirmed_cases)) %>% 
    mutate(formal_date = as.numeric(as.character(as.Date(date, '%m/%d/%Y'), format="%Y%m%d"))) %>% 
    mutate(time = formal_date-min(formal_date)) %>% 
    dplyr::select(region = country_region, date, time, cases) %>% 
    arrange(time)
  
  df.r
}

df.test = df.region(df, region.index[15])
df.china = df.region(df, region.index[30])
```

## optimization

```{r coordinate-wise}
f.logit=function(x, beta){
  a = beta[1]
  b = beta[2]
  c = beta[3]
  a/(1+exp(-b*(x-c)))
}

rss = function(x, y, beta) {
  sum((y-f.logit(x,beta))^2)
}

logitcurve = function(x, y, start, tol = 1e-10, maxiter = 1000) {
  ## start is c(a,b,c)
  ## x is time, y is cases
  cur = start
  rss.cur = rss(x,y,cur)
  rss.prev = Inf
  res = c(0, rss.cur, cur)
  i = 0
  while (i < maxiter && abs(rss.cur - rss.prev) > tol) {
    i = i+1
    prev = cur
    rss.prev = rss.cur
    denom = 1 + exp(-prev[2]*(x-prev[3]))
    cur[1] = sum(y/denom) / sum(1/denom^2)
    y.trans = log(cur[1]/y - 1)
    bc = lm(y.trans~x)$coefficients
    cur[2] = -bc[2]
    cur[3] = bc[1]/cur[2]
    rss.cur = rss(x,y,cur)
    res = rbind(res, c(i, rss.cur, cur))
  }
  res
}

# test
testchina = logitcurve(df.china$time, df.china$cases,start = c(80000,1,86))
beta_hat = c(115253.23,0.02189380,134.52418)
y_hat = f.logit(c(80,0.1,50),df.test$time)
sum((y_hat - df.test$cases)^2)

df.test = df.region(df, region.index[4])
test1 = logitcurve(df.test$time, df.test$cases,start = c(10000,1,40))


# use nls
nls.fit <- nls(cases ~ a/(1+exp(-b*(time-c))), df.region(df, region.index[1]), start = list(a = 1000, b = 1, c = 100))
RSS(nls.fit)
summary(nls.fit)
```

rss coordinate-wise:	25543961352  nls:  460495660


```{r newton}
f.logit=function(beta, t){
  a = beta[1]
  b = beta[2]
  c = beta[3]
  a/(1+exp(-b*(t-c)))
}

# objective function to maximize
obj = function(beta, x, y) {
  a = beta[1]
  b = beta[2]
  c = beta[3]
  
  y.fit = f.logit(beta, x)
  
  2*dot(y, y.fit) - dot(y.fit, y.fit)
}


# objective, gradient and hessian
logisticstuff <- function(x, y, beta) {
  # obj
  obj = obj(beta, x, y)
  # gradient
  f = function(beta) {
      a = beta[1]
      b = beta[2]
      c = beta[3]
      
      y.fit = f.logit(beta, x)
  
      2*dot(y, y.fit) - dot(y.fit, y.fit)
  }
  grad = grad(f, beta)  
  # Hessian
  hess = hessian(f, beta)
 
  return(list(obj = obj, grad = grad, hess = hess))
}

# function to get the optimal beta
logitcurve = function(X, Y, func = logisticstuff, start, tol = 1e-10, maxiter = 200) {
  i <- 0
  cur <- start
  stuff <- func(X, Y, cur)
  res <- c(0, stuff$obj, cur)
  prevobj <- -Inf
  prev = Inf
  while(i < maxiter && abs(stuff$obj - prevobj) > tol) {
    i <- i + 1
    prevobj <- stuff$obj
    prev <- cur
    
    hess = stuff$hess
    while (!is.negative.definite(hess)) {
      hess = hess - 0.1*diag(start)
    }
    
    cur <- prev - solve(hess) %*% stuff$grad
    stuff <- func(X, Y, cur) # obj, gradient, Hessian
    res <- rbind(res, c(i, stuff$obj, cur))
  }
  
  return(res)
}

# test
logitcurve(df.test$time, df.test$cases,start = c(80,0.1,50))
beta_hat = c(80,0.1,50)
y_hat = f.logit(c(80,0.1,50),df.test$time)
mean((y_hat - df.test$cases)^2)
```

```{r newton transformed}
f.logit=function(beta, t){
  a = beta[1]
  b = beta[2]
  c = beta[3]
  a + c*exp(-b*t)
}
transy.fun = function(df) {
  df.trans = df %>% 
    mutate(y = 1/cases)
  
  df.trans
}
china.trans = transy.fun(df.china)
test.trans = transy.fun(df.test)

# objective function to maximize
obj = function(beta, x, y) {
  a = beta[1]
  b = beta[2]
  c = beta[3]
  
  y.fit = f.logit(beta, x)
  
  -sum((y-y.fit)^2) # -RSS
}

# objective, gradient and hessian
logisticstuff <- function(x, y, beta) {
  n = dim(as.array(x))
  a = beta[1]
  b = beta[2]
  c = beta[3]
  # obj
  obj = obj(beta, x, y)
  # gradient
  grad = -c(2*n*a-2*sum(y)+2*c*sum(exp(-b*x)),
           c^2*sum(exp(-2*b*x)*(-2*x))-2*c*sum(y*exp(-b*x)*(-x))+2*a*c*sum(exp(-b*x)*(-x)),
           2*c*sum(exp(-2*b*x))-2*sum(y*exp(-b*x))+2*a*sum(-b*x)
           )
  # Hessian
  hess <- -matrix(c(2*n,
                    2*c*sum(exp(-b*x)*(-x)),
                    2*sum(exp(-b*x)),        
                    2*c*sum(exp(-b*x)*(-x)),
                    c^2*sum(exp(-2*b*x)*4*x^2)-2*c*sum(y*exp(-b*x)*x^2)+2*a*c*sum(exp(-b*x)*x^2),
                    2*c*sum(exp(-2*b*x)*(-2*x))-2*sum(y*exp(-b*x)*(-x))+2*a*sum(exp(-b*x)*(-x)),
                    2*sum(exp(-b*x)),
                    2*c*sum(exp(-2*b*x)*(-2*x))-2*sum(y*exp(-b*x)*(-x))+2*a*sum(exp(-b*x)*(-x)),
                    2*sum(exp(-2*b*x))), ncol=3, byrow = TRUE)
 
  return(list(obj = obj, grad = grad, hess = hess))
}
logisticstuff(test.trans$time, test.trans$y,c(0.01,0.2,270))

# function to get the optimal beta (maximize)
logitcurve = function(X, Y, func = logisticstuff, start, tol = 1e-10, maxiter = 200) {
  i <- 0
  cur <- start
  stuff <- func(X, Y, cur)
  res <- c(0, stuff$obj, cur)
  prevobj <- -Inf
  prev = Inf
  while(i < maxiter && abs(stuff$obj - prevobj) > tol) {
    i <- i + 1
    prevobj <- stuff$obj
    prev <- cur
    
    hess = stuff$hess
    grad = stuff$grad
    while (!is.negative.definite(hess)) {
      hess = hess - diag(start)
    }
    
    cur <- prev - solve(hess) %*% grad
    stuff <- func(X, Y, cur) # obj, gradient, Hessian
    # step-halfing
    l=1
    while(stuff$obj <= prevobj && l < 1000){
      cur <- prev - (1/(2^l))*solve(hess) %*% grad
      stuff = func(X, Y, cur)
      l= l+1
    }
     res <- rbind(res, c(i, stuff$obj, cur))
  }
  
  return(res)
}

# test
beta_hat = c(80000,0.01,80)
a = 1/beta_hat[1]
b = beta_hat[2]
c = exp(b*beta_hat[3]-log(a))
logitcurve(china.trans$time, china.trans$y,start = c(a,b,c))


y_hat = f.logit(c(80,0.1,50),df.test$time)
mean((y_hat - df.test$cases)^2)



# debug
X = test.trans$time
Y = test.trans$y
start = c(0.01,0.2,270)
func = logisticstuff
tol = 1e-10; maxiter = 200
i <- 0
  cur <- start
  stuff <- func(X, Y, cur)
  res <- c(0, stuff$obj, cur)
  prevobj <- -Inf
  prev = Inf
  
  i < maxiter && abs(stuff$obj - prevobj) > tol # loop
i <- i + 1
    prevobj <- stuff$obj
    prev <- cur
    
    hess = stuff$hess
    grad = stuff$grad
    while (!is.negative.definite(hess)) {
      hess = hess - 0.1*diag(start)
    }
    
    cur <- prev - solve(hess) %*% grad
    stuff <- func(X, Y, cur) # obj, gradient, Hessian
    cur
    stuff
    # step-halfing
    l=1
   while(stuff$obj <= prevobj && l < 1000){
     cur <- prev - (1/(4^l))*solve(hess) %*% grad
     stuff = func(X, Y, cur)
     cur
    stuff
     l= l+1
   }

   c(i, stuff$obj, cur)
     res <- rbind(res, c(i, stuff$obj, cur))
```

```{r golden search}
f.logit=function(beta, t){
  a = beta[1]
  b = beta[2]
  c = beta[3]
  a/(1+exp(-b*(t-c)))
}

# RSS
rss = function(beta, x, y) {
  a = beta[1]
  b = beta[2]
  c = beta[3]
  
  y.fit = f.logit(beta, x)
  
  sum((y-y.fit)^2)
}

# -RSS
obj = function(a, x, y) {
  lm.fit = lm(log(a/y-1)~x)
  b = -lm.fit$coefficients[2]
  c = lm.fit$coefficients[1]/b
  beta = c(a,b,c)
  y.fit = f.logit(beta, x)
  
  -sum((y-y.fit)^2)
}
obj(80000,df.china$time, df.china$cases)
# use nls
nls.fit <- nls(cases ~ a/(1+exp(-b*(time-c))), df.region(df, region.index[30]), start = list(a = 80000, b = 0.1, c = 100))
RSS(nls.fit)
nls.y = predict(nls.fit)
summary(nls.fit)

# optimization a
logitcurve = function(x,y, startq1, startq2,tol = 1e-5, maxiter = 10000) {
  i = 0
  q1 = startq1
  q2 = startq2
  objq1 = obj(q1,x,y)
  objq2 = obj(q2,x,y)
  res <- c(0, objq1, objq2, q1, q2)
  while(i < maxiter && abs(objq1 - objq2) > tol && q2-q1 >= 0.5) {
    i <- i + 1
    q1.new = 0.382*(q2-q1)+q1
    q2.new = 0.618*(q2-q1)+q1
    objq1.new = obj(q1.new,x,y)
    objq2.new = obj(q2.new,x,y)
    if(objq1.new > objq2.new)
      q2 = q2.new
    else
      q1 = q1.new
    objq1 = obj(q1,x,y)
    objq2 = obj(q2,x,y)
    res <- rbind(res, c(i, objq1, objq2, q1, q2))
  }
  
  a = q1
  lm.fit = lm(log(a/y-1)~x)
  b = -lm.fit$coefficients[2]
  c = lm.fit$coefficients[1]/b
  list(res = res, beta=c(a,b,c, use.names = FALSE))
}


df.test = df.region(df, region.index[9])
test.result = logitcurve(df.test$time,df.test$cases, 1+max(df.test$cases), 10000000,tol = 1e-5, maxiter = 1000)
test.result
beta = c(2045.0000000 ,   0.0275456 , 255.2518002)
y.fit = f.logit(beta, df.test$time)
# use nls
nls.fit <- nls(cases ~ a/(1+exp(-b*(time-c))), df.region(df, region.index[9]), start = list(a = 2045, b = 0.0275, c = 255))
RSS(nls.fit)
summary(nls.fit)
```


